apiVersion: v1
kind: Service
metadata:
  name: {{ include "ivs.fullname" . }}-api
  labels:
    {{- include "ivs.labels" . | nindent 4 }}
    component: api
spec:
  type: {{ .Values.service.type }}
  selector:
    {{- include "ivs.selectorLabels" . | nindent 4 }}
    component: api
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: http
