{{- if .Values.pdb.enabled }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "ivs.fullname" . }}-api
  labels:
    {{- include "ivs.labels" . | nindent 4 }}
spec:
  minAvailable: {{ .Values.pdb.minAvailable }}
  selector:
    matchLabels:
      {{- include "ivs.selectorLabels" . | nindent 6 }}
      component: api
{{- end }}
