{{- if eq .Values.storage.backend "sqlite" }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "ivs.fullname" . }}-data
  labels:
    {{- include "ivs.labels" . | nindent 4 }}
spec:
  accessModes: [ "ReadWriteOnce" ]
  resources:
    requests:
      storage: {{ .Values.storage.sqlite.pvcSize }}
  {{- if .Values.storage.sqlite.storageClass }}
  storageClassName: {{ .Values.storage.sqlite.storageClass | quote }}
  {{- end }}
{{- end }}
